### ISSUE TITLE
1.4 beta 3 - Listen Modul SQL Fehler

### ISSUE THREAD

**Issue by saress** [alnv/fmodul#1]
Legt man ein Frontend-Listen Modul an und wählt eine Sortierreihenfolge (ASC oder DESC) aus, erhält man einen SQL Fehler, da das SQL Statement nicht richtig aufgebaut ist.

`Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id DESC' at line 1 (SELECT * FROM fm_agency_data WHERE pid = 1 AND published = "1" ORDER BY ,id DESC) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
`

Zudem sollte auch geprüft werden, ob bei der Sortierung überhaupt ein Wert ausgewählt ist (ID, Titel, Datum), denn ansonsten kann es sein, dass man z.B. ein "ODER BY ASC" erhält und das führt ebenfalls zu einem Fehler:

`Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC' at line 1 (SELECT * FROM fm_agency_data WHERE pid = 1 AND published = "1" ORDER BY ASC) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295`

Beste Grüße
Sares

**Comment by alnv** [comment]
Sehr seltsam. 

Normalerweise wird die Sortierreihenfolge und Feld, wenn nichts angegebenen ist, trotzdem gesetzt. Standard Wert beim Feld ist es immer die ID. Und die Sortierreihenfolge: DESC.

Ich habe einige test's durchgeführt und kann das Problem nicht reproduzieren.
Welche PHP und MySQL Version hast du im Einsatz?
Ich werde im Frontend Modul bei den Feldern "Sortierung" und "Sortierreihenfolge" ein Standard Wert setzten. ID und DESC. Danach sollte der Fehler nicht mehr kommen.

**Comment by saress** [comment]
Hallo Alexander,

im ersten Beispiel oben ist die ID ja auch gesetzt worden, nur hat sich vor der ID der Beistrich  eingeschlichen und das führt zu dem Fehler.

Ich habe folgende Versionen im Einsatz (unter MacOS X):

Contao: 3.5.6
MySQL: 5.5.28-log
PHP Version 5.5.29

Beste Grüße
Sares

**Comment by alnv** [comment]
Der Fehler wurde beseitigt. Die Sortierreihenfolge sowie die Sortierfelder haben nun einen Standardwert bereits in der Eingabemaske.
