### ISSUE TITLE
Extension Repository installiert V 1.1.0

### ISSUE THREAD

**Issue by saress** [alnv/fmodul#2]
Versucht man bei einer frischen Contao 3.5.6 LTS Version über die Erweiterungsverwaltung das F-Modul zu installieren, erhält man eine relativ alte Version 1.1.0 und das führt in weiterer Folge zu Problemen.

Beste Grüße
Saress

**Comment by alnv** [comment]
Die 1.1.0 ist in Wirklichkeit 1.3.3 Version im ER. Ich habe mich bereits auf Composer und Contao 4 eingestellt. Aber es hat sich herausgestellt, dass 3.5 (LTS) immer noch für neue Projekte eingesetzt wird. Daher werde ich die Versionierung im ER normal Fortsetzen. Die nächste Version ist die 1.4.0.
Danke für den Hinweis.

**Comment by saress** [comment]
Gerne. Bei mir hat die Installation der ER Version allerdings dazu geführt, dass bei der Installation nicht alle Tabellen angelegt wurden, daher habe ich die 1.4. beta 3 dann händisch installiert und da hat dann alles auf Anhieb funktioniert.
