### ISSUE TITLE
Eine Frage zum dca

### ISSUE THREAD

**Issue by felixpfeiffer** [alnv/fmodul#3]
Hallo, die Erweiterung klingt echt spannend.

Aus der wirklich extrem umfangreichen Beschreibung konnte ich aber nicht erkennen, ob es auch möglich ist z.B. save-Callbacks zu nutzen. Also bei Speicherung eines Datensatzes die Eingabe in einem Feld weiterzuverarbeiten und zusätzlich abzuspeichern oder vor dem speichern zu modifizieren.

Ein kurzer Hinweis zur Machbarkeit wäre super.

**Comment by alnv** [comment]
Das F Modul legt keine DCA Dateien an. Diese sind nur im "Speicher" drin. Auch ist die Tabellen Bezeichnung anders: "fm_tablename" statt "tl_tablename".

Dennoch kann man Callbacks nutzen. Dazu kannst du ein Modul anlegen und dort in die "config.php" den "loadDataContainer" Hook eintragen:

`$GLOBALS['TL_HOOKS']['loadDataContainer'][] = array('meineKlasse', 'dcaErweitern');`

In der "dcaErweitern" Methode kannst du sobald das DCA geladen ist, diesen auch erweitern. 

```
public function dcaErweitern($dca){
 if($dca == 'fm_tablename')
 {
  $GLOBALS['TL_DCA']['fm_tablename']['config']['onsubmit_callback'][] = array('meineKlasse','machEtwas');
 }
}
```

Wenn das F Modul ein BE Modul anlegt erstellt er zwei DCA's
fm_tablename => für den Wrapper
fm_tablename_data => für die Datensätze

Mit diesen kannst du weiter arbeiten. Allerdings habe ich noch nie das F Modul auf diese Weise erweitert. Daher bin ich mir unsicher, wie weit man da gehen kann. Aber ich habe es gerade grob getestet und es scheint zu funktionieren.

Ich hoffe ich konnte deine Frage beantworten.

**Comment by felixpfeiffer** [comment]
Das sieht gut aus. Ich denke dass ich damit arbeiten kann.

Vielen Dank für die schnelle Antwort.
