### ISSUE TITLE
Frage zum List-Modul

### ISSUE THREAD

**Issue by chriza** [alnv/fmodul#4]
Ich möchte mehrere List-Module zu ein und dem gleichen Wrapper mit unterschiedlichen SQL Abfragen auf einer Seite darstellen. Das funktioniert leider nicht - es wird in allen List-Modulen das Ergebnis der SQL Abfrage des auf der Seite zuerst eingebundenen Moduls dargestellt.

In Ihrer Dokumentation schreiben Sie, daß die Wrapper nicht zur Kategorisierung eingesetzt werden sollen.

**Comment by alnv** [comment]
Hast du für jedes List-Modul ein eigenes Frontend-Modul erstellt? Jedenfalls solltest du für jede SQL-Abfrage ein eigenes Frontend-Modul anlegen.  Oder verstehe ich die Frage falsch?

**Comment by chriza** [comment]
Ja habe ich. Die Module beinhalten unterschiedliche SQL Abfragen.

**Comment by alnv** [comment]
Ich werde es reproduzieren und Dir das Ergebnis mitteilen. 

Wenn du magst kannst du auf der F-Modul Demoseite ein Beispiel mit deinem beschriebenen Problem erstellen. Ich werde es mir anschauen und gegebenenfalls fixen und Dir weiterhelfen.

Demo: https://fmodul.alexandernaumov.de/demo.html
Benutzer: demo
Passwort: demofmodule

Die 59min-Countdown wurde deaktiviert.

**Comment by chriza** [comment]
Vielen lieben Dank.
Ich habe mich auch schon eingeloggt und wollte  zwei neue Module anlegen. Habe aber die Rechte nicht.

**Comment by alnv** [comment]
Das sollte eigentlich nicht vorkommen. 
Wenn du dich hier anmeldest: http://demo-fmodule.alexandernaumov.de/contao
Mit diesem Benutzer: demo
Solltest du alle Admin Rechte besitzen.
Ansonsten kannst du auf vorhandene Module zurückgreifen.

**Comment by chriza** [comment]
Wer lesen kann...

Habe das Problem nachstellen können.

Auf der Front-End-Seite http://demo-fmodule.alexandernaumov.de/de/zander-testseite.html
ist das Ergebnis.

Bitte auf der Seite Zander Testseite das erste Modul ausblenden...

Die Module heißen

Zander Liste 1 und Zander Liste 2

**Comment by alnv** [comment]
Vielen Dank. Jetzt sehe ich das Problem. Ich werde es versuchen schnellstmöglich zu fixen.
Noch ein Hinweis:
Wenn du keine Taxonomies benutzt, kannst du diese deaktivieren und das Problem ist behoben.
Siehe Änderungsprotokoll: https://www.alexandernaumov.de/blog/f-modul-v1-aenderungsprotokoll
Bei "F Modul v1.8.0" findest du eine Beschreibung und ein Screenshot.

-> [Screenshot öffnen](https://files.alexandernaumov.de/files/media/Taxonomies-Deaktivieren.png)

**Comment by alnv** [comment]
Problem behoben.
